### PR TITLE
bug: C preprocessor does not propagate directives to executables

### LINKED ISSUE #774: bug: C preprocessor does not propagate directives to executables
### Description

Compiling a C executable that makes use of preprocessor directives does not propage the arguments from `--c-flag` during compilation of the executable.

The preprocessor works as expected for the `library` target.

This behaviour is **NOT** present with Fortran preprocessor directives

### Expected Behaviour

Propage preprocessor directives used to compile the library to the compilation of executables

### Version of fpm

e3fff650ed5983fa0d480cf1cf7d7b0eb08ec417

### Platform and Architecture

Linux x64

### Additional Information

MWE

**fpm.toml***
```toml
name = "fpm-preproc-bug"
version = "0.1.0"
license = "license"
author = "gnikit"
maintainer = "giannis.nikiteas@gmail.com"
copyright = "Copyright 2022, gnikit"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
[install]
library = false
[library]
include-dir = ["src"]

[[executable]]
name="mwe-c"
main="main.c"

[[executable]]
name="mwe-f90"
main="main.F90"
```
**src/val.h**
```h
#ifndef _VAL_H_
#define _VAL_H_

#ifdef VAL
const int variable = 1;
#else
const int variable = 0;
#endif
#endif
```

**src/valf.h**
```h
#ifdef VAL
integer, parameter :: variable = 1
#else
integer, parameter :: variable = 0
#endif
```

**app/main.c**
```c
#include <stdio.h>
#include "val.h"

int main(){
    printf("%d\n", variable);
}
```

**app/main.F90**
```fortran
program main
#include "valf.h"
    print*, variable
end program main
```

```sh
$ fpm run mwe-c --c-flag="-DVAL"
main.F90                               done.
mwe-f90                                done.
[100%] Project compiled successfully.
0
```
[fpm-preproc-bug.zip](https://github.com/fortran-lang/fpm/files/9740510/fpm-preproc-bug.zip)

### PR DESCRIPTION
**Pull request by gnikit**
Fixes #774

### CODE REVIEW

**Review by zoziha — APPROVED** [review]
Thanks for sharing @gnikit .

**Review by awvwgk — COMMENTED** [review]
Can we have one of the example packages testing this be behavior?

**Comment by gnikit** [comment]
> Can we have one of the example packages testing this be behavior?

ok I'll push an example

**Comment by gnikit** [comment]
@awvwgk The existing `c_main` example in main can replicate this, since it incorrectly calls gfortran instead of gcc and thus generates a series of warnings 

```log
 + mkdir -p build/dependencies
 <INFO> BUILD_NAME: build/gfortran
 <INFO> COMPILER:  gfortran
 <INFO> C COMPILER:  gcc
 <INFO> CXX COMPILER: g++
 <INFO> COMPILER OPTIONS:   -Wall -Wextra -Wimplicit-interface -fPIC -fmax-errors=1 -g -fcheck=bounds -fcheck=array-temps -fbacktrace -fcoarray=single
 <INFO> C COMPILER OPTIONS:  
 <INFO> CXX COMPILER OPTIONS: 
 <INFO> LINKER OPTIONS:  
 <INFO> INCLUDE DIRECTORIES:  []
 + mkdir -p build/gfortran_2A42023B310FA28D
[  0%]                         main.c
 + mkdir -p build/gfortran_2A42023B310FA28D/c-main/
 + gfortran -c app/main.c  -Wall -Wextra -Wimplicit-interface -fPIC -fmax-errors=1 -g -fcheck=bounds -fcheck=array-temps -fbacktrace -fcoarray=single -J build/gfortran_2A42023B310FA28D -Ibuild/gfortran_2A42023B310FA28D -o build/gfortran_2A42023B310FA28D/c-main/app_main.c.o
cc1: warning: command-line option ‘-Wimplicit-interface’ is valid for Fortran but not for C
cc1: warning: command-line option ‘-fcheck=array-temps’ is valid for Fortran but not for C
cc1: warning: command-line option ‘-fbacktrace’ is valid for Fortran but not for C
cc1: warning: command-line option ‘-fcoarray=single’ is valid for Fortran but not for C
[ 50%]                         main.c  done.
[ 50%]                         c-main
 + mkdir -p build/gfortran_2A42023B310FA28D/app/
 + gfortran  -Wall -Wextra -Wimplicit-interface -fPIC -fmax-errors=1 -g -fcheck=bounds -fcheck=array-temps -fbacktrace -fcoarray=single  build/gfortran_2A42023B310FA28D/c-main/app_main.c.o  -o build/gfortran_2A42023B310FA28D/app/c-main
[100%]                         c-main  done.
[100%] Project compiled successfully.
 + build/gfortran_2A42023B310FA28D/app/c-main
```

**Comment by zoziha** [comment]
For example, setting a `c-flag` with macro definitions to ensure that `main.c` is compiled correctly? If the `c-flag` is not correctly applied to `main.c`, will the compilation report an error?

**Comment by gnikit** [comment]
> For example, setting a `c-flag` with macro definitions to ensure that `main.c` is compiled correctly? If the `c-flag` is not correctly applied to `main.c`, will the compilation report an error?

Sure we can add something like that. Do the examples run as part of our test suite?

**Comment by zoziha** [comment]
Yes, we can refer to [add_example_package](https://github.com/fortran-lang/fpm/pull/733/commits/8d695c595a984563dd66da0d1502001bc32a1c8c) and [add_example_to_run_in_ci](https://github.com/fortran-lang/fpm/pull/733/commits/ecac6ca4cd8082a39e50f1e77922c0f449724f2f), these example packages are declared and run in `ci/run_tests.sh`, which will start [the test at GitHub Actions](https://github.com/fortran-lang/fpm/blob/e3fff650ed5983fa0d480cf1cf7d7b0eb08ec417/.github/workflows/CI.yml#L134).

**Comment by zoziha** [comment]
It seems that because there are no object files that need to be packaged into `libc_main_preprocess.a`, the `ar` usage on `macOS` is wrong, which may be a bug of `fpm`.

**Comment by gnikit** [comment]
> It seems that because there are no object files that need to be packaged into `libc_main_preprocess.a`, the `ar` usage on `macOS` is wrong, which may be a bug of `fpm`.

Yes, potentially. Another potential bug is that if you add `preprocessor.cpp` macros in the config file, fpm does not pick those up for C. I will file this separately

**Comment by gnikit** [comment]
@zoziha For now I might just add an empty stub .c file to circumvent this

**Comment by zoziha** [comment]
Maybe moving `val.h` to the `include` folder (which is the default C-language header folder for `fpm`) can temporarily fix the problem, and remove the `include-dir='src'` statement in `fpm.toml`.
(See [my temp commit](https://github.com/zoziha/fpm/commit/c2bfd65bd9127e8572a4bc55f4e10c33c25ff8d0) and [passed CI](https://github.com/zoziha/fpm/actions/runs/3233899726/jobs/5296345625#step:15:468))

**Comment by gnikit** [comment]
> Maybe moving `val.h` to the `include` folder (which is the default C-language header folder for `fpm`) can temporarily fix the problem, and remove the `include-dir='src'` statement in `fpm.toml`.

Whatever you want, I'm okay either way.

**Comment by gnikit** [comment]
If everyone is happy with this you can go ahead and merge.

I would leave my test setup as it is just so we can have commit [9d0b31d](https://github.com/fortran-lang/fpm/pull/775/commits/9d0b31d7cf697b403f2abf4e238693534fbbeddf) in the history to inspect why the OS X CI failed and whether it's an fpm bug.

File: src/fpm_targets.f90 [hunk 1]
```diff
@@ -268,7 +268,15 @@ subroutine build_target_list(targets,model)
...
+                        exe_type = FPM_TARGET_C_OBJECT
+                    else if (str_ends_with(lower(sources(i)%file_name), [".cpp", ".cc "])) then
+                        exe_type = FPM_TARGET_CPP_OBJECT
+                    else    ! Default to a Fortran object
+                        exe_type = FPM_TARGET_OBJECT
+                    end if
+
+                    call add_target(targets,package=model%packages(j)%name,type = exe_type,&
                                 output_name = get_object_name(sources(i)), &
                                 source = sources(i) &
```
Comment (LKedward) [inline src/fpm_targets.f90:281]: Not 100% sure, but I think #777 might be because of a missing macros line here:

```suggestion
                                source = sources(i), &
                                macros = model%packages(j)%macros &
```

Does that seem right @arteevraina?

Comment (arteevraina) [reply src/fpm_targets.f90:281]: Yes, adding that line should resolve it for the executables. Currently, macros were not passed to executables.

Comment (gnikit) [reply src/fpm_targets.f90:281]: Thanks guys for this. @LKedward can you merge this PR and I'll open a new one addressing #777
