### PR TITLE
Give Programs Access to Code in Subdirectories

### LINKED ISSUE #408: Cannot Find Modules in Subdirectories of Tests or Executables
If there are modules in sub-directories of a test or executable, fpm reports that it cannot find them.

```
[pop-os:~/tmp/test_subdirectories] tree
.
├── app
│   ├── main.f90
│   └── sub
│       └── file.f90
├── fpm.toml
├── README.md
├── src
│   └── test_subdirectories.f90
└── test
    ├── check.f90
    └── sub
        └── something.f90

5 directories, 7 files
[pop-os:~/tmp/test_subdirectories] fpm run
 + mkdir -p build/dependencies
Unable to find source for module dependency: "thing_m" used by "app/main.f90"
ERROR STOP 1

Error termination. Backtrace:
#0  0x47eb9d in ???
#1  0x47ee35 in ???
#2  0x47fdde in ???
#3  0x406276 in __fpm_MOD_cmd_run
	at src/fpm.f90:226
#4  0x400890 in MAIN__
	at app/main.f90:28
#5  0x400890 in main
	at app/main.f90:9
[pop-os:~/tmp/test_subdirectories] fpm test
Unable to find source for module dependency: "thing_m" used by "app/main.f90"
ERROR STOP 1

Error termination. Backtrace:
#0  0x47eb9d in ???
#1  0x47ee35 in ???
#2  0x47fdde in ???
#3  0x406276 in __fpm_MOD_cmd_run
	at src/fpm.f90:226
#4  0x400861 in MAIN__
	at app/main.f90:30
#5  0x400861 in main
	at app/main.f90:9
```

I was under the impression that this was meant to work.

### PR DESCRIPTION
**Pull request by everythingfunctional**
Programs can now use modules in subdirectories from their location. I.e. a program `app/main.f90` can use a module `app/sub_dir/mod.f90`. This applies to tests and examples as well.

Fix #408

### CODE REVIEW

**Comment by everythingfunctional** [comment]
Sorry about the noisy change set. My editor is set to automatically remove trailing whitespace.

File: fpm/src/fpm_targets.f90 [hunk 1]
```diff
@@ -409,7 +409,7 @@ function find_module_dependency(targets,module_name,include_dir) result(target_p
                     exit
                 case default
                     if (present(include_dir)) then
-                        if (dirname(targets(k)%ptr%source%file_name) == include_dir) then
+                        if (index(dirname(targets(k)%ptr%source%file_name), include_dir) > 0) then ! source file is within the include_dir or a subdirectory
```
Comment (awvwgk) [inline fpm/src/fpm_targets.f90:412]: Should we check if index is 1 rather than larger zero? A match at position 10 could be a false positive.

Comment (everythingfunctional) [reply fpm/src/fpm_targets.f90:412]: I suppose that's true. Good catch.

**Review by milancurcic — APPROVED** [review]

File: fpm/test/fpm_test/test_module_dependencies.f90 [hunk 2]
```diff
@@ -356,19 +356,19 @@ subroutine test_invalid_library_use(error)
...
                                     provides=[string_t('my_mod')], &
                                     uses=[string_t('app_mod')])
 
         call targets_from_sources(targets,model,error)
-        
+
     end subroutine test_invalid_library_use
 
 
     !> Check program using a non-library module in a different directory
```
Comment (LKedward) [inline fpm/test/fpm_test/test_module_dependencies.f90:370]:
```suggestion
    !> Check program using a non-library module in a subdirectory
```

File: fpm/src/fpm_targets.f90 [hunk 3]
```diff
@@ -314,22 +314,22 @@ subroutine add_dependency(target, dependency)
...
+!>
 !> - Library sources (`FPM_SCOPE_LIB`) may only use modules
 !>   also with library scope. This includes library modules
 !>   from dependencies.
 !>
 !> - Executable sources (`FPM_SCOPE_APP`,`FPM_SCOPE_TEST`) may use
 !>   library modules (including dependencies) as well as any modules
-!>   corresponding to source files __in the same directory__ as the 
+!>   corresponding to source files __in the same directory__ as the
 !>   executable source.
```
Comment (LKedward) [inline fpm/src/fpm_targets.f90:333]:
```suggestion
!>   corresponding to source files in the same directory or a 
!>   subdirectory of the executable source file.
```

**Review by LKedward — APPROVED** [review]
Many thanks. This all looks good to me. My only request is are you able to add a failing test for a program using a module in a parent directory, to cover all conditions.

**Comment by everythingfunctional** [comment]
I've added the test and updated the doc string as suggested. Thanks for the great reviews guys. I'll give you guys a few hours in case you want to double check the changes and merge later today.

**Review by awvwgk — APPROVED** [review]
