### PR TITLE
Fix enumeration of non-library link objects

### LINKED ISSUE #263: Failure to build iso_varying_string
I wanted to see how well the Fortran version was doing (I haven't really used it at all yet). I tried building my [iso_varying_string](https://gitlab.com/everythingfunctional/iso_varying_string) package and got the following error.

```
 + gfortran  build/gfortran_debug/test/unit_test_main.f90.o build/gfortran_debug/test/unit_test_adjustl_test.f90.o build/gfortran_debug/test/unit_test_adjustr_test.f90.o build/gfortran_debug/test/unit_test_assignment_test.f90.o build/gfortran_debug/test/unit_test_char_test.f90.o build/gfortran_debug/test/unit_test_concat_test.f90.o build/gfortran_debug/test/unit_test_equal_test.f90.o build/gfortran_debug/test/unit_test_extract_test.f90.o build/gfortran_debug/test/unit_test_greater_than_equal_test.f90.o build/gfortran_debug/test/unit_test_greater_than_test.f90.o build/gfortran_debug/test/unit_test_iachar_test.f90.o build/gfortran_debug/test/unit_test_ichar_test.f90.o build/gfortran_debug/test/unit_test_index_test.f90.o build/gfortran_debug/test/unit_test_insert_test.f90.o build/gfortran_debug/test/unit_test_len_test.f90.o build/gfortran_debug/test/unit_test_len_trim_test.f90.o build/gfortran_debug/test/unit_test_less_than_equal_test.f90.o build/gfortran_debug/test/unit_test_less_than_test.f90.o build/gfortran_debug/test/unit_test_lge_test.f90.o build/gfortran_debug/test/unit_test_lgt_test.f90.o build/gfortran_debug/test/unit_test_lle_test.f90.o build/gfortran_debug/test/unit_test_llt_test.f90.o build/gfortran_debug/test/unit_test_not_equal_test.f90.o build/gfortran_debug/test/unit_test_remove_test.f90.o build/gfortran_debug/test/unit_test_repeat_test.f90.o build/gfortran_debug/test/unit_test_replace_range_test.f90.o build/gfortran_debug/test/unit_test_replace_start_test.f90.o build/gfortran_debug/test/unit_test_replace_target_test.f90.o build/gfortran_debug/test/unit_test_scan_test.f90.o build/gfortran_debug/test/unit_test_split_character_set_test.f90.o build/gfortran_debug/test/unit_test_split_string_set_test.f90.o build/gfortran_debug/test/unit_test_trim_test.f90.o build/gfortran_debug/test/unit_test_var_str_test.f90.o build/gfortran_debug/test/unit_test_verify_test.f90.o -Wall -Wextra -Wimplicit-interface  -fPIC -fmax-errors=1 -g -fbounds-check -fcheck-array-temporaries -fbacktrace -Jbuild/gfortran_debug/iso_varying_string build/gfortran_debug/iso_varying_string/libiso_varying_string.a  -o build/gfortran_debug/test/unit_test
Undefined symbols for architecture x86_64:
  "___custom_generator_MOD___vtab_3126CD9", referenced from:
      ___repeat_test_MOD_test_repeat in unit_test_repeat_test.f90.o
  "___custom_generator_MOD___vtab_custom_generator_Ascii_character_generator_t", referenced from:
      ___iachar_test_MOD_test_iachar in unit_test_iachar_test.f90.o
      ___ichar_test_MOD_test_ichar in unit_test_ichar_test.f90.o
  "___custom_generator_MOD___vtab_custom_generator_Ascii_string_pair_generator_t", referenced from:
      ___concat_test_MOD_test_concat in unit_test_concat_test.f90.o
      ___equal_test_MOD_test_equals in unit_test_equal_test.f90.o
      ___greater_than_equal_test_MOD_test_greater_than_equals in unit_test_greater_than_equal_test.f90.o
      ___greater_than_test_MOD_test_greater_than in unit_test_greater_than_test.f90.o
      ___index_test_MOD_test_index in unit_test_index_test.f90.o
      ___less_than_equal_test_MOD_test_less_than_equals in unit_test_less_than_equal_test.f90.o
      ___less_than_test_MOD_test_less_than in unit_test_less_than_test.f90.o
      ...
  "___custom_generator_MOD___vtab_custom_generator_Character_input_t", referenced from:
      ___iachar_test_MOD_check_iachar in unit_test_iachar_test.f90.o
      ___ichar_test_MOD_check_ichar in unit_test_ichar_test.f90.o
  "___custom_generator_MOD___vtab_custom_generator_String_and_integer_input_t", referenced from:
      ___repeat_test_MOD_check_repeat in unit_test_repeat_test.f90.o
  "___custom_generator_MOD___vtab_custom_generator_String_pair_input_t", referenced from:
      ___concat_test_MOD_check_concat_character_and_string in unit_test_concat_test.f90.o
      ___concat_test_MOD_check_concat_string_and_character in unit_test_concat_test.f90.o
      ___concat_test_MOD_check_concat_strings in unit_test_concat_test.f90.o
      ___equal_test_MOD_check_string_equal_character in unit_test_equal_test.f90.o
      ___equal_test_MOD_check_character_equal_string in unit_test_equal_test.f90.o
      ___equal_test_MOD_check_string_equal_string in unit_test_equal_test.f90.o
      ___greater_than_equal_test_MOD_check_string_greater_than_equal_character in unit_test_greater_than_equal_test.f90.o
      ...
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
 Command failed
ERROR STOP 

Error termination. Backtrace:
#0  0x106e70ebd
#1  0x106e71b75
#2  0x106e72f03
#3  0x106dbb9f8
#4  0x106da8810
#5  0x106da90b2
#6  0x106da7a0f
#7  0x106e3d894
```

This error is from MacOS, but a similar one is emitted on Linux. I suspect an issue with ordering of things in the link command, but I'm not sure.

### PR DESCRIPTION
**Pull request by LKedward**
- Fixes #263 caused by missing out some non-library dependencies in `link_objects` list for executable targets.
- Update target dependency test-suite to build and check the `link_objects` list for link targets
- Update `hello_complex_2` example package to include an indirectly use'd non-library module dependency

[iso_varying_string](https://gitlab.com/everythingfunctional/iso_varying_string) now builds with Fortran `fpm` and unit tests pass (`fpm test unit_test`).

### CODE REVIEW

**Comment by everythingfunctional** [comment]
👍  Thanks for fixing it @LKedward

File: fpm/test/fpm_test/test_module_dependencies.f90 [hunk 1]
```diff
@@ -71,14 +72,17 @@ subroutine test_library_module_use(error)
         if (allocated(error)) then
             return
         end if
-
+
```
Comment (awvwgk) [inline fpm/test/fpm_test/test_module_dependencies.f90:75]: Trailing whitespace

**Review by awvwgk — COMMENTED** [review]
Looks good to me.

Just one whitespace comment from me.

**Review by awvwgk — APPROVED** [review]

File: fpm/test/fpm_test/test_module_dependencies.f90 (hunk 1 above)
Comment (LKedward) [reply fpm/test/fpm_test/test_module_dependencies.f90:75]:
```suggestion

```

**Comment by LKedward** [comment]
Thanks for reviewing @awvwgk. I'll merge later today if there are no more comments.
